import type { Metadata } from "next";
import { Inter, Playfair } from "next/font/google";
import "./globals.css";
import { inter } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-violet-100"}>{children}</body>
    </html>
  );
}
